name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log into docker-hub
      run: docker login --username nidomiro --password ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --tag nidomiro/hugo-asciidoctor:latest

    - name: Push the Docker image
      run: docker push nidomiro/hugo-asciidoctor:latest
